server:

  affinity: ""
  ha:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "dynamodb" {
        ha_enabled = "true"
        access_key = "${RELEASE_VAULT_AWS_ACCESS_KEY_ID}"
        secret_key = "${RELEASE_VAULT_AWS_SECRET_ACCESS_KEY}"
        table      = "${RELEASE_VAULT_DATABASE}"
        region     = "${RELEASE_CLUSTER_REGION}"
      }

      service_registration "kubernetes" {}

      seal "awskms" {
        access_key = "${RELEASE_VAULT_AWS_ACCESS_KEY_ID}"
        secret_key = "${RELEASE_VAULT_AWS_SECRET_ACCESS_KEY}"
        kms_key_id = "${RELEASE_VAULT_KMS_ARN}"
        region     = "${RELEASE_CLUSTER_REGION}"
      }
