server:

  extraEnvironmentVars:
    AWS_ROLE_SESSION_NAME: s3vault

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::443786448530:role/release/iam_for_vaults3bucket

  affinity: ""
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        service_registration "kubernetes" {}

        storage "raft" {
          path    = "/vault/data"
        }

        seal "awskms" {
          region     = "us-east-1"
          kms_key_id = "arn:aws:kms:us-east-1:443786448530:alias/release/release-handsup-us-east-1"
        }
