server:

  extraEnvironmentVars:
    AWS_ROLE_SESSION_NAME: s3vault

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::443786448530:role/release/release-handsup-us-east-1-vault-unseal

  affinity: ""
  ha:
    enabled: true
    config: |
      ui = true

      service_registration "kubernetes" {}

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      seal "awskms" {
        region     = "us-east-1"
        kms_key_id = "release/release-handsup-us-east-1"
      }
