dist: xenial
language: python
python: 3.7
install:
- pip3 install -r requirements.txt
- pip3 install codecov
- python3 setup.py install
script:
- make test
after_success:
- codecov
deploy:
- provider: pypi
  user: amundsen-dev
  password:
    secure: zIFmsUEvMgxG/gxmswAno4Y8MnfSAMGYGTAw4V4iAVthKqkLZHuyARDtl/zSpbiSlcfd8UcWvrvQ8WJDDd09iXRB/QGxz2CmVxBpUh9NT5NOWmgFg2cc7GUc7CyTP94QrSZWOFVGlGt9PHCZsvXh2gTTTUTEvQ3t9G56isCyMrfYbS+csCx3ffFeW+Wu/bTHK/azMLPldho/EOjgGrUUOC1nW5l9K92IXg0T/pYg6aDXlJ7l+ds+9R/Gehh/lz/j46pHimUdDTGa39EO52/VMQwzDbENmM8S6W0lQpXUAxx80s45mnmE2TihTzKOjB0aZJ20arxnPwcBrWZC78M7+nBjlPftDIY4kvFFP6Mim3XNTQLnvwtSMA3erjoawyb8QIQA+SgeNRKvRcJrBBVOuQsKeY4ScNxO3XQlhAP6nF7ATuUFAY8lsLAgVGwo5VBvGodzuY9mm3NtX9RT4fh2LMBlE20sgcwvi6lFPsoI0061UwhAjThQbx25txXGcn3rTIX+N2WCJpcuw0vMOSCZApUhC6B56bThlpwe9+mHboMrws+kAJLyefymaj4jbKq+ex+nFIP6HQ1LfXmsIVPnR5571pIqfWkqxJfW+Lmrh39QeEIEG1o7pNvMv05wP9/Jo98S4QOQk8iO+omHuBIsaNRS/84ZmkWktnt8AuQw6NE=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: lyft/amundsenmetadatalibrary
- provider: script
  script: docker login -u amundsendev -p $DOCKER_LOGIN_PASSWORD && make build-push-image
  on:
    branch: master
    tags: true
    repo: lyft/amundsenmetadatalibrary
env:
  global:
    secure: qK+qtPjx419eBBhqH2mRPHTkEVgKirw4kC5uil2Z/uuXElTdQMqMbrjGb7SmeYOI41bmq5j6rOgZs6EBVHrIlJXFVITAcr3mbBpOanaMVSdQf6cCcUZ622idKNk1kdlcSeoYyBmLs2PWa43XK8mX6bgcjbivRI6S79FLdK3NffEt17ERDnlL5Ud8QIUnYepw4oB5pKUjCGiz0T9VlKpEPiB51UUBRNfLmQnhLjwQJ29H3GBoI4YAC4B5w2az0YGADg3xqmMs2agsV+mMbHR0NqSoZdyX4t69ffrEjOtimlZ6TgRR7hHmTCUNx1MLRlx2B/M07Dl9T2fD2LINzlwXC24YtubaoQBSj+ufyYdqLr14SV99NiaG18uGGXbth+fucO7CK5V0J4eXnBB/9ZaMmVBH6Zp0bVJwSl+ppf8yklqRsC9J6og7gAMaIAgH9OyeYgZzuTRJXzbJpSCOSx7GcX2zwlpyvqoi5/hIv6R8dz0CE/lqxgnQz4LqH9dwgiPFB9ogIs++TJcSy81QMyvJDWvS5mzQLRNAZCXt70HQiZmuj9XQnE3RBIQw15yznwWYmiczRsJj7VKgQ4Ul/BfgY6igDyPSTJDFOBf6qnoC3jRgqf/Ecg0C6paehC4YoyBHyd9aywKxrtnWPytQGcs9BbU1IuZyshwinhSxbaw3v4c=
