dist: xenial
language: python
python: 3.7
install:
- pip3 install -r requirements.txt
- pip3 install codecov
- python3 setup.py install
script:
- make test
after_success:
- codecov
deploy:
  provider: pypi
  user: amundsen-dev
  password:
    secure: zIFmsUEvMgxG/gxmswAno4Y8MnfSAMGYGTAw4V4iAVthKqkLZHuyARDtl/zSpbiSlcfd8UcWvrvQ8WJDDd09iXRB/QGxz2CmVxBpUh9NT5NOWmgFg2cc7GUc7CyTP94QrSZWOFVGlGt9PHCZsvXh2gTTTUTEvQ3t9G56isCyMrfYbS+csCx3ffFeW+Wu/bTHK/azMLPldho/EOjgGrUUOC1nW5l9K92IXg0T/pYg6aDXlJ7l+ds+9R/Gehh/lz/j46pHimUdDTGa39EO52/VMQwzDbENmM8S6W0lQpXUAxx80s45mnmE2TihTzKOjB0aZJ20arxnPwcBrWZC78M7+nBjlPftDIY4kvFFP6Mim3XNTQLnvwtSMA3erjoawyb8QIQA+SgeNRKvRcJrBBVOuQsKeY4ScNxO3XQlhAP6nF7ATuUFAY8lsLAgVGwo5VBvGodzuY9mm3NtX9RT4fh2LMBlE20sgcwvi6lFPsoI0061UwhAjThQbx25txXGcn3rTIX+N2WCJpcuw0vMOSCZApUhC6B56bThlpwe9+mHboMrws+kAJLyefymaj4jbKq+ex+nFIP6HQ1LfXmsIVPnR5571pIqfWkqxJfW+Lmrh39QeEIEG1o7pNvMv05wP9/Jo98S4QOQk8iO+omHuBIsaNRS/84ZmkWktnt8AuQw6NE=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: lyft/amundsenmetadatalibrary
after_success:
  - codecov
