apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app: {{ template "amundsen.name" . }}
    component: {{ .Values.frontEnd.serviceName }}
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  FRONTEND_BASE: {{ .Values.frontEnd.baseUrl }}
  {{ if .Values.frontEnd.config.class }}
  FRONTEND_SVC_CONFIG_MODULE_CLASS: {{ .Values.frontEnd.config.class }}
  {{ end }}
  SEARCHSERVICE_BASE: http://{{ .Chart.Name }}-{{ .Values.search.serviceName }}:5001
  METADATASERVICE_BASE: http://{{ .Chart.Name }}-{{ .Values.metadata.serviceName }}:5002
  LONG_RANDOM_STRING: {{ quote .Values.LONG_RANDOM_STRING }}
  {{ if .Values.flaskApp.module }}
  APP_WRAPPER: {{ .Values.flaskApp.module }}
  {{ end }}
  {{ if .Values.flaskApp.class }}
  APP_WRAPPER_CLASS: {{ .Values.flaskApp.class }}
  {{ end }}
  {{ if .Values.frontEnd.ALL_UNEDITABLE_SCHEMAS }}
  ALL_UNEDITABLE_SCHEMAS: {{ .Values.frontEnd.ALL_UNEDITABLE_SCHEMAS }}
  {{ end }}
  {{ if .Values.oidc.enabled }}
  FLASK_APP_MODULE_NAME: flaskoidc
  FLASK_APP_CLASS_NAME: FlaskOIDC
  FLASK_OIDC_CLIENT_ID: {{ .Values.oidc.frontend.client_id }}
  FLASK_OIDC_CLIENT_SECRET: {{ .Values.oidc.frontend.client_secret }}
{{ toYaml .Values.oidc.configs | indent 2 }}
  {{ end }}
{{ if .Values.frontEnd.envVars }}
{{ toYaml .Values.frontEnd.envVars | indent 2 }}
{{ end }}
