apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app: {{ template "amundsen.name" . }}
    component: {{ .Values.frontEnd.serviceName }}
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  FRONTEND_BASE: {{ .Values.frontEnd.baseUrl }}
  {{ if .Values.frontEnd.config.class }}
  FRONTEND_SVC_CONFIG_MODULE_CLASS: {{ .Values.frontEnd.config.class }}
  {{ end }}
  SEARCHSERVICE_BASE: http://{{ .Chart.Name }}-{{ .Values.search.serviceName }}:5001
  METADATASERVICE_BASE: http://{{ .Chart.Name }}-{{ .Values.metadata.serviceName }}:5002
  LONG_RANDOM_STRING: {{ quote .Values.LONG_RANDOM_STRING }}
  {{ if .Values.flaskApp.module }}
  APP_WRAPPER: {{ .Values.flaskApp.module }}
  {{ end }}
  {{ if .Values.flaskApp.class }}
  APP_WRAPPER_CLASS: {{ .Values.flaskApp.class }}
  {{ end }}
  {{ if .Values.frontEnd.ALL_UNEDITABLE_SCHEMAS }}
  ALL_UNEDITABLE_SCHEMAS: {{ .Values.frontEnd.ALL_UNEDITABLE_SCHEMAS }}
  {{ end }}
  {{ if .Values.oidc.enabled }}
  FLASK_APP_MODULE_NAME: flaskoidc
  FLASK_APP_CLASS_NAME: FlaskOIDC
  FLASK_OIDC_CLIENT_ID: {{ .Values.oidc.frontend.client_id }}
  FLASK_OIDC_CLIENT_SECRET: {{ .Values.oidc.frontend.client_secret }}
{{ toYaml .Values.oidc.configs | indent 2 }}
  {{ end }}
{{ if .Values.frontEnd.envVars }}
{{ toYaml .Values.frontEnd.envVars | indent 2 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.metadata.serviceName }}
  labels:
    app: {{ include "amundsen.name" . }}
    component: {{ include "amundsen.fullname" . }}
    chart: {{ include "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PROXY_HOST: {{ if .Values.metadata.proxy.host }}{{ .Values.metadata.proxy.host }}{{ else }}bolt://{{ .Release.Name }}-neo4j.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}{{ end }}
  {{ if .Values.metadata.proxy.port }}
  PROXY_PORT: {{ .Values.metadata.proxy.port }}
  {{ end }}
  {{ if .Values.metadata.proxy.user }}
  CREDENTIALS_PROXY_USER: {{ .Values.metadata.proxy.user }}
  {{ end }}
  {{ if .Values.metadata.proxy.password }}
  CREDENTIALS_PROXY_PASSWORD: {{ .Values.metadata.proxy.password }}
  {{ end }}
  {{ if .Values.flaskApp.module }}
  FLASK_APP_MODULE_NAME: {{ .Values.flaskApp.module }}
  {{ end }}
  {{ if .Values.flaskApp.class }}
  FLASK_APP_CLASS_NAME: {{ .Values.flaskApp.class }}
  {{ end }}
  {{ if .Values.oidc.enabled }}
  FLASK_APP_MODULE_NAME: flaskoidc
  FLASK_APP_CLASS_NAME: FlaskOIDC
  FLASK_OIDC_CLIENT_ID: {{ .Values.oidc.metadata.client_id }}
  FLASK_OIDC_CLIENT_SECRET: {{ .Values.oidc.metadata.client_secret }}
{{ toYaml .Values.oidc.configs | indent 2 }}
  {{ end }}
{{ if .Values.metadata.envVars }}
{{ toYaml .Values.metadata.envVars | indent 2 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.search.serviceName }}
  labels:
    app: {{ include "amundsen.name" . }}
    component: {{ include "amundsen.fullname" . }}
    chart: {{ include "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PROXY_ENDPOINT: {{ if .Values.search.proxy.endpoint }}{{ .Values.search.proxy.endpoint }}{{ else }}{{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}{{ end }}
  {{ if .Values.search.proxy.user }}
  CREDENTIALS_PROXY_USER: {{ .Values.search.proxy.user }}
  {{ end }}
  {{ if .Values.search.proxy.password }}
  CREDENTIALS_PROXY_PASSWORD: {{ .Values.search.proxy.password }}
  {{ end }}

  {{ if .Values.flaskApp.module }}
  FLASK_APP_MODULE_NAME: {{ .Values.flaskApp.module }}
  {{ end }}
  {{ if .Values.flaskApp.class }}
  FLASK_APP_CLASS_NAME: {{ .Values.flaskApp.class }}
  {{ end }}
  {{ if .Values.oidc.enabled }}
  FLASK_APP_MODULE_NAME: flaskoidc
  FLASK_APP_CLASS_NAME: FlaskOIDC
  FLASK_OIDC_CLIENT_ID: {{ .Values.oidc.search.client_id }}
  FLASK_OIDC_CLIENT_SECRET: {{ .Values.oidc.search.client_secret }}
{{ toYaml .Values.oidc.configs | indent 2 }}
  {{ end }}
{{ if .Values.search.envVars }}
{{ toYaml .Values.search.envVars | indent 2 }}
{{ end }}
