{{ if .Values.neo4j.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: {{ template "amundsen.name" . }}
    component: neo4j
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "amundsen.name" . }}
      component: neo4j
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      {{- with default .Values.podAnnotations .Values.neo4j.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "amundsen.name" . }}
        component: neo4j
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.neo4j.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.neo4j.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.neo4j.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      initContainers:
        - name: init-neo4j-plugins
          image: {{ .Values.neo4j.initPluginsContainer.image }}:{{ .Values.neo4j.initPluginsContainer.imageTag }}
          imagePullPolicy: "IfNotPresent"
          command:
            {{- .Values.neo4j.initPluginsContainer.command | toYaml | nindent 12 }}
          volumeMounts:
            - name: plugins
              mountPath: /var/lib/neo4j/plugins
      containers:
      - name: neo4j
        image: {{ .Values.neo4j.image }}:{{ .Values.neo4j.imageTag }}
        ports:
        - containerPort: 7474
        - containerPort: 7687
        - containerPort: 1337
        env:
          - name: NEO4J_CONF
            value: "/conf"
        volumeMounts:
        - name: conf
          mountPath: /conf
        {{- if .Values.neo4j.persistence }}
        - name: data
          mountPath: /var/lib/neo4j/data
        {{- end}}
        - name: plugins
          mountPath: /var/lib/neo4j/plugins
        {{- with .Values.neo4j.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end}}
      volumes:
        - name: conf
          configMap:
            name: neo4j-configmap
        {{- if .Values.neo4j.persistence }}
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-pvc
        {{- end}}
        - name: plugins
          emptyDir: {}
{{ end }}
