apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "amundsen.fullname" . }}-{{ .Values.metadata.serviceName }}
  labels:
    app: {{ template "amundsen.name" . }}
    component: {{ .Values.metadata.serviceName }}
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "amundsen.name" . }}
      component: {{ .Values.metadata.serviceName }}
      release: {{ .Release.Name }}
  replicas: {{ default 1 .Values.metadata.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-metadata.yaml") . | sha256sum }}
      {{- with default .Values.podAnnotations .Values.metadata.podAnnotations }}
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "amundsen.name" . }}
        component: {{ .Values.metadata.serviceName }}
        release: {{ .Release.Name }}
    spec:
      {{- with default .Values.nodeSelector .Values.metadata.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.metadata.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.metadata.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- if .Values.metadata.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.metadata.imagePullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.metadata.serviceName }}
        image: {{ .Values.metadata.image }}:{{ .Values.metadata.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
          - configMapRef:
              name: {{ template "amundsen.fullname" . }}-{{ .Values.metadata.serviceName }}
        livenessProbe:
          httpGet:
            path: "/healthcheck"
            port: 5002
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        {{- with .Values.metadata.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
