version: '3'
services:
  atlas:
      image: wbaa/rokku-dev-apache-atlas:latest
      container_name: atlas_amundsen
      ports:
          - 21000:21000
      networks:
        - amundsennet
      environment:
        - ATLAS_PROVISION_EXAMPLES=true
  amundsensearch:
      image: amundsendev/amundsen-search:latest
      container_name: amundsensearch
      ports:
        - 5001:5000
      #depends_on:
      #  - elasticsearch
      networks:
        - amundsennet
  amundsenmetadata:
      image: amundsendev/amundsen-metadata:latest
      container_name: amundsenmetadata
      depends_on:
        - atlas
      ports:
        - 5002:5000
      networks:
        - amundsennet
      environment:
        - CREDENTIALS_PROXY_USER=admin
        - CREDENTIALS_PROXY_PASSWORD=admin
        - PROXY_HOST=atlas
        - PROXY_PORT=21000
        - PROXY_CLIENT=ATLAS
  amundsenfrontend:
      image: amundsendev/amundsen-frontend:latest
      container_name: amundsenfrontend
      depends_on:
        - amundsenmetadata
        - amundsensearch
      ports:
        - 5000:5000
      networks:
        - amundsennet
      environment:
        - METADATASERVICE_BASE=http://amundsenmetadata:5000
        - SEARCHSERVICE_BASE=http://amundsensearch:5000
networks:
  amundsennet:
