version: '3'
services:
  atlas:
    # the image comes from https://github.com/ing-bank/rokku-dev-apache-atlas
    # it might take some time for Atlas to start
    image: wbaa/rokku-dev-apache-atlas:0.1.5
    container_name: atlas
    ports:
      - 21000:21000
    networks:
      - amundsennet
    environment:
      - ATLAS_KICKSTART_AMUNDSEN=true
  amundsensearch:
    build:
      context: .
      dockerfile: Dockerfile.search.public
    container_name: amundsensearch
    depends_on:
      - elasticsearch
    ports:
      - 5001:5001
    environment:
      - PROXY_ENDPOINT=es_amundsen_atlas
    networks:
      - amundsennet
  amundsenmetadata:
    build:
      context: .
      dockerfile: Dockerfile.metadata.public
    container_name: amundsenmetadata
    ports:
      - 5002:5002
    networks:
      - amundsennet
    environment:
      - CREDENTIALS_PROXY_USER=admin
      - CREDENTIALS_PROXY_PASSWORD=admin
      - PROXY_HOST=atlas
      - PROXY_PORT=21000
      - PROXY_ENCRYPTED=False
      - PROXY_CLIENT=ATLAS
      - METADATA_SVC_CONFIG_MODULE_CLASS=metadata_service.config.AtlasConfig
  amundsenfrontend:
    build:
      context: .
      args:
        SEARCHSERVICE_BASE: http://amundsensearch:5001
        METADATASERVICE_BASE: http://amundsenmetadata:5002
      dockerfile: Dockerfile.frontend.local
    container_name: amundsenfrontend
    depends_on:
      - amundsenmetadata
      - amundsensearch
    ports:
      - 5000:5000
    networks:
      - amundsennet
    environment:
      - METADATASERVICE_BASE=http://amundsenmetadata:5002
      - SEARCHSERVICE_BASE=http://amundsensearch:5001
  elasticsearch:
    image: elasticsearch:6.7.0
    container_name: es_amundsen_atlas
    ports:
      - 9200:9200
    networks:
      - amundsennet
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
networks:
  amundsennet:
