apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      run: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Chart.Name }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
          - name: NEO4J_AUTH
            value: "neo4j/test"
          - name: NEO4J_CONF
            value: "/conf"
        volumeMounts:
        - name: conf
          mountPath: /conf
        {{- if (or (kindIs "invalid" .Values.neo4jpvc) .Values.neo4jpvc)}}
        - name: data
          mountPath: /var/lib/neo4j/data
        {{- end}}
      volumes:
        - name: conf
          configMap:
            name: {{ .Chart.Name }}-configmap
        {{- if (or (kindIs "invalid" .Values.neo4jpvc) .Values.neo4jpvc)}}
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-pvc
        {{- end}}
      {{- with .Values.resources }}
      resources:
{{ toYaml . | indent 8 }}
      {{- end }}
