{{- if .Values.neo4j.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: neo4j-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: "{{ default "" .Values.neo4j.persistence.storageClass }}"
    resources:
        requests:
            storage: {{ default "3Gi" .Values.neo4j.persistence.size }}
{{- end -}}