name: Tests

on: [push]

jobs:
  unit:
    name: unit
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      with:
        python-version: 3.7
      - name: 'Install dependencies'
        run: pip install -r requirements.txt
      - name: 'Install project'
        run: python setup.py install
      - name: 'Run tests'
        run: make test_unit
  codecov:
    name: codecov
    runs-on: ubuntu-16.04
    needs: unit
    steps:
      - uses: actions/checkout@v1
      with:
        python-version: 3.7
      - name: 'Install codecov'
        run: pip install codecov
      - name: 'Push coverage'
        run: codecov
