export const MORE_BUTTON_TEXT = 'More options';
export const REQUEST_DESCRIPTION_TEXT = 'Request Column Description';
export const EMPTY_MESSAGE = 'There are no available columns for this table';
export const EDITABLE_SECTION_TITLE = 'Description';
export const COLUMN_STATS_TITLE = 'Column Statistics';
export const COLUMN_LINEAGE_LIST_SIZE = 5;
export const COLUMN_LINEAGE_DOWNSTREAM_TITLE = `Top ${COLUMN_LINEAGE_LIST_SIZE} Downstream Columns`;
export const COLUMN_LINEAGE_UPSTREAM_TITLE = `Top ${COLUMN_LINEAGE_LIST_SIZE} Upstream Columns`;
export const COLUMN_LINEAGE_MORE_TEXT = 'See More';
