export const APPLICATIONS_LABEL = 'Applications';
export const AIRFLOW = 'Airflow';
export const DATABRICKS = 'Databricks';
export const PRODUCING = 'producing';
export const CONSUMING = 'consuming';
export const DAG_LABEL = 'DAG';
export const TASK_LABEL = 'Task';
export const NOT_AVAILABLE_VALUE = 'Not Available';
export const DELAY_SHOW_POPOVER_MS = 500;
