name: Monthly Release

on:
  schedule:
    - cron: 15 20 19 * *
  workflow_dispatch:
    logLevel:
      description: "Log level"
      required: true
      default: "warning"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          semantic-release publish
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create new release
          title: Create new release
          body: |
            - Bumped version for new release of FE library.

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: new-release
