dependencies:
#  - name: neo4j
#    version: 1.2.2
#    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: elasticsearch
    version: 1.32.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elasticsearch.enabled
