dependencies:
#  - name: neo4j
#    version: 1.2.2
#    repository: https://charts.helm.sh/stable/
  - name: elasticsearch
    version: 7.13.4
    repository:  https://helm.elastic.co
    condition: elasticsearch.enabled
