apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app: "neo4j"
data:
  neo4j.conf: |-
    apoc.import.file.enabled=true
    cypher.forbid_shortestpath_common_nodes=false
    dbms.connector.bolt.enabled=true
    dbms.connector.http.enabled=true
    dbms.connector.https.enabled=true
    dbms.connectors.default_listen_address=0.0.0.0
    dbms.directories.import=/mnt
    dbms.jvm.additional=-Djdk.tls.ephemeralDHKeySize=2048
    dbms.jvm.additional=-Dunsupported.dbms.udc.source=tarball
    dbms.jvm.additional=-XX:+AlwaysPreTouch
    dbms.jvm.additional=-XX:+DisableExplicitGC
    dbms.jvm.additional=-XX:+UseG1GC
    dbms.logs.query.enabled=true
    dbms.logs.query.rotation.keep_number=7
    dbms.logs.query.rotation.size=20m
    dbms.memory.heap.initial_size=23000m
    dbms.memory.heap.max_size=23000m
    dbms.memory.pagecache.size=26600m
    dbms.security.allow_csv_import_from_file_urls=true
    dbms.security.procedures.unrestricted=algo.*,apoc.*
    dbms.windows_service_name=neo4j  
    apoc.export.file.enabled=true
    apoc.import.file.enabled=true