version: '3'
services:
  neo4j:
      image: neo4j:3.5.26
      environment:
        - NEO4J_AUTH=neo4j/test
        - NEO4J_dbms_active__database=amundsen.db
        - NEO4J_dbms_directories_data=/data
        - NEO4J_dbms_directories_logs=/logs
        - NEO4J_dbms_directories_import=/var/lib/neo4j/import
        - NEO4J_dbms_security_auth__enabled=false
        - NEO4J_dbms_connectors_default__listen__address=0.0.0.0
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsen-neo4j
          awslogs-region: us-west-2
          awslogs-stream-prefix: amundsen-neo4j

  elasticsearch:
      image: elasticsearch:6.7.0
      ports:
          - 9200:9200
      ulimits:
        nofile:
           soft: 65536
           hard: 65536
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsen-elasticsearch
          awslogs-region: us-west-2
          awslogs-stream-prefix: amundsen-elasticsearch

  amundsensearch:
      image: amundsendev/amundsen-search:2.11.1
      ports:
        - 5001:5000
      environment:
        - PROXY_ENDPOINT=elasticsearch
      command: gunicorn -w 2 --bind :5000 search_service.search_wsgi
      links:
        - elasticsearch:elasticsearch
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsensearch
          awslogs-region: us-west-2
          awslogs-stream-prefix: amundsensearch

  amundsenmetadata:
      image: amundsendev/amundsen-metadata:3.9.0
      ports:
        - 5002:5000
      environment:
         - PROXY_HOST=bolt://neo4j
      command: gunicorn -w 2 --bind :5000 metadata_service.metadata_wsgi
      links:
        - neo4j:neo4j
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsenmetadata
          awslogs-region: us-west-2
          awslogs-stream-prefix: amundsenmetadata

  amundsenfrontend:
      image: amundsendev/amundsen-frontend:3.12.0
      ports:
        - 5000:5000
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5000
        - METADATASERVICE_BASE=http://amundsenmetadata:5000
      links:
        - amundsensearch:amundsensearch
        - amundsenmetadata:amundsenmetadata
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsenfrontend
          awslogs-region: us-west-2
          awslogs-stream-prefix: amundsenfrontend


