environment: "dev"
provider: aws
dnsZone: teamname.company.com
dockerhubImagePath: amundsendev

LONG_RANDOM_STRING: 1234

# To enable auth via OIDC, set this to true. 
oidcEnabled: false
# OIDC needs some configuration. If you want the chart to make your secrets, set this to true and set the next four values. 
# If you don't want to configure your secrets via helm, you can still use the oidc_config.yaml as a template
createOidcSecret: false
# OIDC_CLIENT_ID: 
# OIDC_CLIENT_SECRET: 
# OIDC_ORG_URL: 
# OIDC_AUTH_SERVER_ID: 

## Support Node, affinity and tolerations for scheduler pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
nodeSelector: {}
affinity: {}
tolerations: []

searchServiceName: search
searchImageVersion: 1.4.2
search:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []

metadataServiceName: metadata
metadataImageVersion: 1.1.6
metadata:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  # You can also set these properties to override the ones set above
  nodeSelector: {}
  affinity: {}
  tolerations: []

frontEndServiceName: frontend
frontEndImageVersion: 1.2.0
frontEndServicePort: 80
frontEnd:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  # You can also set these properties to override the ones set above
  nodeSelector: {}
  affinity: {}
  tolerations: []
