# Because the mono-repo has different test suites for each sub-project,
# it is challenging to use Github's required status checks. For example,
# the front-end specifies node tests, and we'd like to gate PR on their passing.
# However, none of the other projects have those tests. Thus, if you require
# the front-end tests to pass, it will be impossible to land non-frontend PRs.
# However, Github helpfully has the behavior where if there are multiple test
# runners with a single name, if any of them fail, the whole PR will fail. Thus
# this file specifies dummy tests that will always pass.

# See also:
# * https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586/4
# * https://github.community/t/feature-request-conditional-required-checks/16761/2

name: Dummy Front-end tests
on: pull_request
jobs:
  test-unit-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: exit 0
